# Generated by Django 4.1.7 on 2023-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0003_order_customer_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='asset_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Vacant', 'Vacant'), ('Disposed', 'Disposed'), ('Borrowed', 'Borrowed')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Vacant', 'Vacant'), ('Disposed', 'Disposed'), ('Borrowed', 'Borrowed')], max_length=200, null=True),
        ),
    ]
