# Generated by Django 4.1.7 on 2023-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0004_remove_product_date_created_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('PJ 5th', 'PJ 5th'), ('PJ 7th', 'PJ 7th'), ('PJ 11th', 'PJ 11th'), ('PG', 'PG'), ('IPH', 'IPH'), ('SBN', 'SBN'), ('MLK', 'MLK'), ('BP', 'BP'), ('JB', 'JB'), ('KT', 'KT'), ('Sabah', 'Sabah'), ('SRK', 'SRK')], max_length=200, null=True),
        ),
    ]
