# Generated by Django 4.1.7 on 2023-03-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0005_alter_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
