# Generated by Django 4.1.7 on 2023-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0006_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('Monitor', 'Monitor'), ('Headset', 'Headset'), ('Laptop', 'Laptop')], max_length=200, null=True),
        ),
    ]
