# Generated by Django 4.1.7 on 2023-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_start',
            field=models.DateField(null=True),
        ),
    ]
