# Generated by Django 4.1.7 on 2023-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0008_alter_product_warranty_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_start',
            field=models.DateTimeField(null=True),
        ),
    ]
