# Generated by Django 4.1.7 on 2023-03-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0009_alter_product_warranty_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_start',
            field=models.DateField(null=True),
        ),
    ]
