# Generated by Django 4.1.7 on 2023-03-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0010_alter_customer_date_created_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('ACC & Finance', 'ACC & Finance'), ('Admin', 'Admin'), ('Collection', 'Collection'), ('Credit', 'Credit'), ('CS', 'CS'), ('Marketing', 'Marketing'), ('Mgmt', 'Mgmt'), ('HR', 'HR'), ('Mgmt', 'Mgmt'), ('Planning', 'Planning'), ('IT', 'IT')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resign', 'Resign')], max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testasset.staff'),
        ),
    ]
