# Generated by Django 4.1.7 on 2023-03-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0011_staff_remove_order_customer_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Senior Executive', 'Senior Executive'), ('Team Lead', 'Team Lead'), ('A.Manager', 'A.Manager'), ('Manager', 'Manager'), ('MD', 'MD')], max_length=200, null=True),
        ),
    ]
