# Generated by Django 4.1.7 on 2023-03-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0012_staff_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Asset',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='asset',
        ),
    ]
