# Generated by Django 4.1.7 on 2023-03-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0014_categories_alter_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
