# Generated by Django 4.1.7 on 2023-03-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0015_alter_categories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='category',
            new_name='categories',
        ),
    ]
