# Generated by Django 4.1.7 on 2023-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0016_rename_category_asset_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
