# Generated by Django 4.1.7 on 2023-04-04 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0018_rename_date_created_order_date_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_assigned',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='asset',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testasset.staff'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
