# Generated by Django 4.1.7 on 2023-04-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0019_asset_date_assigned_asset_staff_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='staff',
            field=models.ForeignKey(default='Keep Server Room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='testasset.staff'),
        ),
    ]
