# Generated by Django 4.1.7 on 2023-04-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0027_alter_asset_asset_no_alter_asset_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_created',
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testasset.staff'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Vacant', 'Vacant'), ('Disposed', 'Disposed'), ('Borrowed', 'Borrowed')], default='Vacant', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resign', 'Resign')], default='Active', max_length=200, null=True),
        ),
    ]
