# Generated by Django 4.1.7 on 2023-04-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0028_remove_asset_date_assigned_remove_staff_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
