# Generated by Django 4.1.7 on 2023-04-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0029_alter_staff_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_no',
            field=models.CharField(blank=True, default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, default=None, max_length=10, unique=True),
        ),
    ]
