# Generated by Django 4.1.7 on 2023-04-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0037_alter_asset_asset_no_alter_asset_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='testasset.categories'),
        ),
    ]
