# Generated by Django 4.1.7 on 2023-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0039_department_alter_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(choices=[('PJ 5th', 'PJ 5th'), ('PJ 7th', 'PJ 7th'), ('PJ 11th', 'PJ 11th'), ('PG', 'PG'), ('IPH', 'IPH'), ('SBN', 'SBN'), ('MLK', 'MLK'), ('BP', 'BP'), ('JB', 'JB'), ('KT', 'KT'), ('Sabah', 'Sabah'), ('SRK', 'SRK')], max_length=200, null=True),
        ),
    ]
