# Generated by Django 4.1.7 on 2023-05-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0044_alter_staff_pirnter_pw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='pirnter_pw',
            new_name='printer_pw',
        ),
    ]
