# Generated by Django 4.1.7 on 2023-05-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0047_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='warranty_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='warranty_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='asset_no',
            new_name='title',
        ),
    ]
