# Generated by Django 4.1.7 on 2023-05-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0048_rename_warranty_end_event_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='asset_no',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='warranty_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='warranty_start',
        ),
    ]
