# Generated by Django 4.1.7 on 2023-06-21 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testasset', '0049_rename_title_event_asset_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_predict', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='testasset.department')),
            ],
        ),
    ]
